@echo off
touch 7zip.md
touch autohotkey.md
touch calibre.md
touch chocolateyGUI.md
touch clink.md
touch cmder.md
touch dependencywalker.md
touch ditto.md
touch dropbox.md
touch fiddler.md
touch filezilla.md
touch firefox.md
touch genymotion.md
touch gnuWin.md
touch googleChrome.md
touch greenshot.md
touch keepass.md
touch kickAssVim.md
touch markdownpad2.md
touch microsoftSecurityEssentials.md
touch mongodb.md
touch mpc_hc.md
touch nunitTestAdapter.md
touch paint.net.md
touch picasa.md
touch powerShell.md
touch productifyPowerTools2013.md
touch putty.md
touch scriptcs.md
touch slowCheetahXml.md
touch sourceTree.md
touch spotify.md
touch sysinternals.md
touch trillian.md
touch truecrypt.md
touch vSCommandsForVisualStudio.md
touch vlc.md
touch vsspellchecker.md
touch which.md
touch winDirStat.md
touch windowsLiveWriter.md
touch winmerge.md

