theme: jekyll-theme-slate
description: {{site.github.project_tagline}}
title: Quintussential
show_fork: true

collections:
    software:
        output: true
        permalink: /pages/:collection/:name
