backend:
  name: github
  repo: jquintus/jquintus.github.io
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://quintussential.com/

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }